# Site settings
title: I am joking, seriously.
email: momocy.w@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a blog of "iamjoking", and I am glad to share with you my experiences.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://iamjoking.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  iamjoking
author_name:	iamjoking

favicon:     "/images/favicon.ico"

# Build settings
markdown: kramdown
# highlighter: pygments

paginate: 4
paginate_path: "page:num"